### ISSUE TITLE
ios list command used in framework is not working

### ISSUE THREAD

**Issue by mohakbarokar** [znsio/teswiz#877]
Getting exception as following:

Exception in thread "main" java.lang.IllegalStateException: Not a JSON Object: null
        at com.google.gson.JsonElement.getAsJsonObject(JsonElement.java:165)
        at com.znsio.teswiz.runner.LocalDevicesSetup.getListOfIOSDevices(LocalDevicesSetup.java:96)
        at com.znsio.teswiz.runner.LocalDevicesSetup.getConnectedIOSDevices(LocalDevicesSetup.java:88)
        at com.znsio.teswiz.runner.LocalDevicesSetup.setupLocalIOSExecution(LocalDevicesSetup.java:109)
        at com.znsio.teswiz.runner.DeviceSetup.setupIOSExecution(DeviceSetup.java:395)
        at com.znsio.teswiz.runner.Setup.setupExecutionEnvironment(Setup.java:255)
        at com.znsio.teswiz.runner.Setup.getExecutionArguments(Setup.java:172)
        at com.znsio.teswiz.runner.Runner.<init>(Runner.java:54)
        at com.znsio.teswiz.runner.Runner.main(Runner.java:204)
 
while debugging i found that FW is hitting "ios list" command which is not getting recognised in my machine. also ios executable binary is not available under "/opt/homebrew/bin/ios"

**Comment by anandbagmar** [comment]
@mohakbarokar Share your config, capabilities file and also the command you are running.

**Comment by mohakbarokar** [comment]
@anandbagmar  I am trying to run existing tests tagged for iOS. 

With Command: CONFIG=./configs/helloworld/helloworld_local_ios_config.properties TAG="@helloWorld" PLATFORM=iOS ./gradlew run

The issue I observed is in /opt/homebrew/bin folder ios package is not getting installed. I also searched for this binary over internet but could't find it.

**Comment by anandbagmar** [comment]
Try `npm install -g go-ios `

**Comment by mohakbarokar** [comment]
Thanks @anandbagmar its working now
